version: 2
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "yarn.lock" }}
            - v1-dependency-cache-
      - run: yarn
      - run: echo "Checking if lockfiles changed..." && git diff --exit-code
      - run: npm rebuild node-sass
      - save_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/yarn
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: '.'
          paths:
            - yarn.lock
            - packages/*/node_modules

  compile-libs:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "yarn.lock" }}
            - v1-dependency-cache-
      - run: yarn compile-libs
      - persist_to_workspace:
          root: '.'
          paths:
            - packages/*/dist
            - packages/*/src/generated

  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "yarn.lock" }}
            - v1-dependency-cache-
      - run: yarn lint

  dist:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn dist
      - persist_to_workspace:
          root: '.'
          paths:
            - yarn.lock
            - packages/core/dist
            - packages/datetime/dist
            - packages/docs/dist
            - packages/labs/dist
            - packages/table/dist

  test-core:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lerna run test --scope '@blueprintjs/core'

  test-datetime:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lerna run test --scope '@blueprintjs/datetime'

  test-labs:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lerna run test --scope '@blueprintjs/labs'

  test-table:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lerna run test --scope '@blueprintjs/table'

  # dummy job to make the fan-in part of the workflow easy to declare
  accept-verify:
    docker:
      - image: circleci/node:8
    steps:
      - run: exit 0

  deploy-preview:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - deploy: ./scripts/submit-preview-comment

  deploy-npm:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - deploy: ./scripts/publish-npm-semver-tagged

workflows:
  version: 2
  compile_lint_test_dist_deploy:
    jobs:
      - install-dependencies
      - compile-libs:
          requires: [install-dependencies]
      - lint:
          requires: [install-dependencies]
      - dist:
          requires: [compile-libs]
      - test-core:
          requires: [compile-libs]
      - test-datetime:
          requires: [compile-libs]
      - test-labs:
          requires: [compile-libs]
      - test-table:
          requires: [compile-libs]
      - accept-verify:
          requires:
            - lint
            - dist
            - test-core
            - test-datetime
            - test-labs
            - test-table
      - deploy-preview:
          requires: [accept-verify]
      - deploy-npm:
          requires: [accept-verify]
          filters:
            tags:
              only:
                - /^release-.*/
            branches:
              ignore:
                - /.*/
